import moment from 'moment'
import { v1 as uuidv1 } from 'uuid';
export const data = [{
         uid: uuidv1(),
         productName: 'Santa Clause X1100',
         brand: 'Santa Clause',
         purchasedDate:moment().subtract(10, 'days').calendar(),
         price: 3500.5,
         offeredPrice: 2500.5,
         expriationDate:moment().subtract(8, 'days').calendar(),
         totalBaches: '4',
         quantity: '3500',
         priceperunit: 1250.5,
         unitSize: '1',
         unitType: 'unit',
         number: 3453453,
          actions: 'edit/delete',
          batchRecord: [
            {
              brandId: uuidv1(),
              created: moment('2018-06-03').format('MM/DD/YYYY'),
              expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
              quantity: 45,
              inventory: 'Safe',
              unitType: 'unit',
              vendor: {
                id: '345345',
                name: 'Ravi Kumar',
                companyName: 'tecHindustan',
                joined: '<moment date>',
               },
              price: 1250.5,
            },
            {
              brandId: uuidv1(),
              created: moment('2018-06-03').format('MM/DD/YYYY'),
              expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
              quantity: 35,
              inventory: 'Safe',
              unitType: 'gram',
              vendor: {
                id: '43534535',
                name: 'Ravi Kumar',
                companyName: 'tecHindustan',
                joined: '<moment date>',
              },
              price: 1250.5,
            }
          ]  
        },
        {
         uid: uuidv1(),
         productName: 'Santa Clause X1100',
         brand: 'Santa Clause',
         purchasedDate:moment().subtract(10, 'days').calendar(),
         price: 3500.5,
         offeredPrice: 2500.5,
         expriationDate:moment().subtract(8, 'days').calendar(),
         totalBaches: '4',
         quantity: '3500',
         priceperunit: 1250.5,
         unitSize: '1',
         unitType: 'unit',
         number: 3453453,
          actions: 'edit/delete',
          batchRecord: [
            {
              brandId: uuidv1(),
              created: moment('2018-06-03').format('MM/DD/YYYY'),
              expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
              quantity: 45,
              inventory: 'Safe',
              unitType: 'unit',
              vendor: {
                id: '345345',
                name: 'Ravi Kumar',
                companyName: 'tecHindustan',
                joined: '<moment date>',
               },
              price: 1250.5,
            },
            {
              brandId: uuidv1(),
              created: moment('2018-06-03').format('MM/DD/YYYY'),
              expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
              quantity: 35,
              inventory: 'Safe',
              unitType: 'gram',
              vendor: {
                id: '43534535',
                name: 'Ravi Kumar',
                companyName: 'tecHindustan',
                joined: '<moment date>',
              },
              price: 1250.5,
            }
          ]  
        },
        {
          uid: uuidv1(),
          productName: 'Santa Clause X1100',
          brand: 'Santa Clause',
          purchasedDate:moment().subtract(10, 'days').calendar(),
          price: 3500.5,
          offeredPrice: 2500.5,
          expriationDate:moment().subtract(8, 'days').calendar(),
          totalBaches: '4',
          quantity: '3500',
          priceperunit: 1250.5,
          unitSize: '1',
          unitType: 'unit',
          number: 3453453,
           actions: 'edit/delete',
           batchRecord: [
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 45,
               inventory: 'Safe',
               unitType: 'unit',
               vendor: {
                 id: '345345',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
                },
               price: 1250.5,
             },
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 35,
               inventory: 'Safe',
               unitType: 'gram',
               vendor: {
                 id: '43534535',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
               },
               price: 1250.5,
             }
           ]  
         },
         {
          uid: uuidv1(),
          productName: 'Santa Clause X1100',
          brand: 'Santa Clause',
          purchasedDate:moment().subtract(10, 'days').calendar(),
          price: 3500.5,
          offeredPrice: 2500.5,
          expriationDate:moment().subtract(8, 'days').calendar(),
          totalBaches: '4',
          quantity: '3500',
          priceperunit: 1250.5,
          unitSize: '1',
          unitType: 'unit',
          number: 3453453,
           actions: 'edit/delete',
           batchRecord: [
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 45,
               inventory: 'Safe',
               unitType: 'unit',
               vendor: {
                 id: '345345',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
                },
               price: 1250.5,
             },
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 35,
               inventory: 'Safe',
               unitType: 'gram',
               vendor: {
                 id: '43534535',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
               },
               price: 1250.5,
             }
           ]  
         },
         {
          uid: uuidv1(),
          productName: 'Santa Clause X1100',
          brand: 'Santa Clause',
          purchasedDate:moment().subtract(10, 'days').calendar(),
          price: 3500.5,
          offeredPrice: 2500.5,
          expriationDate:moment().subtract(8, 'days').calendar(),
          totalBaches: '4',
          quantity: '3500',
          priceperunit: 1250.5,
          unitSize: '1',
          unitType: 'unit',
          number: 3453453,
           actions: 'edit/delete',
           batchRecord: [
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 45,
               inventory: 'Safe',
               unitType: 'unit',
               vendor: {
                 id: '345345',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
                },
               price: 1250.5,
             },
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 35,
               inventory: 'Safe',
               unitType: 'gram',
               vendor: {
                 id: '43534535',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
               },
               price: 1250.5,
             }
           ]  
         },
         {
          uid: uuidv1(),
          productName: 'Santa Clause X1100',
          brand: 'Santa Clause',
          purchasedDate:moment().subtract(10, 'days').calendar(),
          price: 3500.5,
          offeredPrice: 2500.5,
          expriationDate:moment().subtract(8, 'days').calendar(),
          totalBaches: '4',
          quantity: '3500',
          priceperunit: 1250.5,
          unitSize: '1',
          unitType: 'unit',
          number: 3453453,
           actions: 'edit/delete',
           batchRecord: [
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 45,
               inventory: 'Safe',
               unitType: 'unit',
               vendor: {
                 id: '345345',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
                },
               price: 1250.5,
             },
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 35,
               inventory: 'Safe',
               unitType: 'gram',
               vendor: {
                 id: '43534535',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
               },
               price: 1250.5,
             }
           ]  
         },
         {
          uid: uuidv1(),
          productName: 'Santa Clause X1100',
          brand: 'Santa Clause',
          purchasedDate:moment().subtract(10, 'days').calendar(),
          price: 3500.5,
          offeredPrice: 2500.5,
          expriationDate:moment().subtract(8, 'days').calendar(),
          totalBaches: '4',
          quantity: '3500',
          priceperunit: 1250.5,
          unitSize: '1',
          unitType: 'unit',
          number: 3453453,
           actions: 'edit/delete',
           batchRecord: [
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 45,
               inventory: 'Safe',
               unitType: 'unit',
               vendor: {
                 id: '345345',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
                },
               price: 1250.5,
             },
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 35,
               inventory: 'Safe',
               unitType: 'gram',
               vendor: {
                 id: '43534535',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
               },
               price: 1250.5,
             }
           ]  
         },
         {
          uid: uuidv1(),
          productName: 'Santa Clause X1100',
          brand: 'Santa Clause',
          purchasedDate:moment().subtract(10, 'days').calendar(),
          price: 3500.5,
          offeredPrice: 2500.5,
          expriationDate:moment().subtract(8, 'days').calendar(),
          totalBaches: '4',
          quantity: '3500',
          priceperunit: 1250.5,
          unitSize: '1',
          unitType: 'unit',
          number: 3453453,
           actions: 'edit/delete',
           batchRecord: [
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 45,
               inventory: 'Safe',
               unitType: 'unit',
               vendor: {
                 id: '345345',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
                },
               price: 1250.5,
             },
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 35,
               inventory: 'Safe',
               unitType: 'gram',
               vendor: {
                 id: '43534535',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
               },
               price: 1250.5,
             }
           ]  
         },
         {
          uid: uuidv1(),
          productName: 'Santa Clause X1100',
          brand: 'Santa Clause',
          purchasedDate:moment().subtract(10, 'days').calendar(),
          price: 3500.5,
          offeredPrice: 2500.5,
          expriationDate:moment().subtract(8, 'days').calendar(),
          totalBaches: '4',
          quantity: '3500',
          priceperunit: 1250.5,
          unitSize: '1',
          unitType: 'unit',
          number: 3453453,
           actions: 'edit/delete',
           batchRecord: [
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 45,
               inventory: 'Safe',
               unitType: 'unit',
               vendor: {
                 id: '345345',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
                },
               price: 1250.5,
             },
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 35,
               inventory: 'Safe',
               unitType: 'gram',
               vendor: {
                 id: '43534535',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
               },
               price: 1250.5,
             }
           ]  
         },
         {
          uid: uuidv1(),
          productName: 'Santa Clause X1100',
          brand: 'Santa Clause',
          purchasedDate:moment().subtract(10, 'days').calendar(),
          price: 3500.5,
          offeredPrice: 2500.5,
          expriationDate:moment().subtract(8, 'days').calendar(),
          totalBaches: '4',
          quantity: '3500',
          priceperunit: 1250.5,
          unitSize: '1',
          unitType: 'unit',
          number: 3453453,
           actions: 'edit/delete',
           batchRecord: [
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 45,
               inventory: 'Safe',
               unitType: 'unit',
               vendor: {
                 id: '345345',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
                },
               price: 1250.5,
             },
             {
               brandId: uuidv1(),
               created: moment('2018-06-03').format('MM/DD/YYYY'),
               expirationDate: moment('2020-08-01').format('MM/DD/YYYY'),
               quantity: 35,
               inventory: 'Safe',
               unitType: 'gram',
               vendor: {
                 id: '43534535',
                 name: 'Ravi Kumar',
                 companyName: 'tecHindustan',
                 joined: '<moment date>',
               },
               price: 1250.5,
             }
           ]  
         },


      ]